version: "3"
services:
  web:
    build:
      # The location of the project. In our case, the working directory
      context: .
      # Filename of the dockerfile
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    # No need for port mapping as tests don't use ports
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
